import type { AgentRun } from "@/types/dashboard";

/**
 * MOCK fixture — a single illustrative snapshot of a retrieval pipeline run.
 * No backend is connected yet (that lands in S5+); this is the only place
 * demo agent state is defined, so components never hardcode status/copy.
 */
export const AGENT_RUNS: readonly AgentRun[] = [
  {
    id: "orchestrator",
    number: 1,
    name: "Orchestrator",
    status: "running",
    activity: "Coordinating agent pipeline",
    logs: ["Received structured command", "Dispatched retrieval tasks", "Awaiting reranking output"],
    progress: null,
    startedAt: "2026-08-02T09:12:03Z",
    endedAt: null,
    error: null,
  },
  {
    id: "emotion",
    number: 2,
    name: "Emotion Agent",
    status: "completed",
    activity: "Voice emotion context ready",
    logs: ["STT stream connected", "Emotion context detected"],
    progress: 100,
    startedAt: "2026-08-02T09:12:04Z",
    endedAt: "2026-08-02T09:12:09Z",
    error: null,
  },
  {
    id: "lexical-retrieval",
    number: 3,
    name: "Lexical Retrieval Agent",
    status: "completed",
    activity: "BM25 search complete",
    logs: ["Queried inverted index", "37 candidates retrieved"],
    progress: 100,
    startedAt: "2026-08-02T09:12:04Z",
    endedAt: "2026-08-02T09:12:08Z",
    error: null,
  },
  {
    id: "ontology",
    number: 4,
    name: "Ontology Agent",
    status: "loading",
    activity: "Resolving term hierarchy",
    logs: ["Loaded biomedical ontology graph", "Mapping entities to UMLS concepts"],
    progress: 62,
    startedAt: "2026-08-02T09:12:09Z",
    endedAt: null,
    error: null,
  },
  {
    id: "re-ranking",
    number: 5,
    name: "Re-ranking Agent",
    status: "waiting",
    activity: "Waiting on retrieval agents",
    logs: [],
    progress: null,
    startedAt: null,
    endedAt: null,
    error: null,
  },
  {
    id: "llm-reasoning",
    number: 6,
    name: "LLM Reasoning Agent",
    status: "queued",
    activity: "Queued for execution",
    logs: [],
    progress: null,
    startedAt: null,
    endedAt: null,
    error: null,
  },
  {
    id: "validation",
    number: 7,
    name: "Validation Agent",
    status: "error",
    activity: "Schema validation failed",
    logs: ["Received draft answer", "Missing citation for claim #2"],
    progress: null,
    startedAt: "2026-08-02T09:12:10Z",
    endedAt: "2026-08-02T09:12:11Z",
    error: "Validation schema mismatch: missing required field 'citations'",
  },
];
